from queryDatabase import state_total, nationwide_total, getTopTenOverall, getTopTenState, getStateData, getWarchestOverall, getWarchestState, listOfContributions, listOfWarchests, totDonByParty
#state_total('TX')
#nationwide_total()
#(total, demP, repP, otherP) = getStateData("TX")
#print(total)
#print(demP)
#print(repP)
#print(otherP)
#getTopTenState("TX")
#getTopTenOverall()
#getWarchestOverall()
#getWarchestState("TX")
#listOfContributions()
#listOfWarchests()
totDonByParty("TX", "DEM")
